### ISSUE TITLE
OracleでNVARCHAR2を使いたい

### ISSUE THREAD

**Issue by ecormaksin** [takezoe/amateras-modeler#10]
便利なプラグインを作ってくださりありがとうございます。

表題のようにデータベースがOracleの場合にNVARCHAR2を使いたい状況が発生しています。

`/net.java.amateras.db/src/net/java/amateras/db/dialect/OracleDialect.java`の29行目における

```java
//new ColumnType("NVARCHAR2", Messages.getResourceString("type.string"),true, Types.NVARCHAR),
```

のコメントアウトを解除し、ビルドしたものをEclipseのpluginsフォルダに配置してクリーン起動したのですがカラムの型に表示されません。
どのようにすればNVARCHAR2を使えるようになるでしょうか。

なお、配置の際は以下のような処理をしています。
- ./binフォルダに生成された`net`フォルダを、プロジェクト フォルダのルートへ移動
- `net.java.amateras.db`フォルダが作成されないようにzip圧縮
- 圧縮されたzipファイルを`net.java.amateras.db_1.0.9.v201909041620.jar`へリネーム

以上、よろしくお願いします。

**Comment by takezoe** [comment]
以下の箇所でDialectからカラムの型を取得して表示していますので、コードの修正自体はそれだけでよいはずです。

https://github.com/takezoe/amateras-modeler/blob/85fba98277cbc8704f46a80a7c3599919e5225bd/net.java.amateras.db/src/net/java/amateras/db/visual/editpart/TableEditDialog.java#L363-L366

> なお、配置の際は以下のような処理をしています。

記述していただいている処理がよく理解できていないのですが、正しいビルド方法については以下のページを参照していただければと思います。
https://github.com/takezoe/amateras-modeler/wiki/How-to-release

**Comment by ecormaksin** [comment]
ご回答ありがとうございました。
