### ISSUE TITLE
Cannot install from update site

### ISSUE THREAD

**Issue by jiangzhishen** [takezoe/amateras-modeler#19]
Unable to read repository at https://takezoe.github.io/amateras-update-site/content.xml.
Unable to read repository at https://takezoe.github.io/amateras-update-site/content.xml.
SOCKS: Connection refused

Eclipse Version: 2021-06 (4.20.0)

**Comment by takezoe** [comment]
Please specify http://takezoe.github.io/amateras-update-site/
