### ISSUE TITLE
Jdk17 and eclipse 2021-12 (4.22.0) Click to create a class diagram, and the "finish" button does not respond

### ISSUE THREAD

**Issue by bailucool** [takezoe/amateras-modeler#22]
Jdk17 and eclipse 2021-12 (4.22.0) Click to create a class diagram, and the "finish" button does not respond
![ED73UF5 Y~H)UT}54F16HEJ](https://user-images.githubusercontent.com/50900472/158029353-e3930f46-7e63-4b9a-b41f-34b74c73b077.png)Amateras UML is updated to the latest version and still cannot be solved

**Comment by bailucool** [comment]
The probability is the version. Don't let me reduce the version

**Comment by junyu33** [comment]
> The probability is the version. Don't let me reduce the version

I've rollbacked eclipse to 2020-06 (4.22.0), but it still doesn't work.

**Comment by bailucool** [comment]
It should be a problem with the JDK version. Look at the update history. If jdk11 is supported, there will be a problem after it is exceeded.

**Comment by junyu33** [comment]
> It should be a problem with the JDK version. Look at the update history. If jdk11 is supported, there will be a problem after it is exceeded.

I installed jdk8 and restarted my computer, and it finally works. Thanks for your help.

**Comment by takezoe** [comment]
It looks an issue of Xstream in JDK 11. It's used for serializing and deserializing the model data as XML in Amateras Modeler. I don't know if we can fix the issue without breaking compatibility but will take a look.

**Comment by bailucool** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by bailucool** [comment]
> It looks an issue of Xstream with JDK 11. Xstream is used for serializing and deserializing the model data as XML in Amateras Modeler. I don't know if we can fix the issue without breaking compatibility but will take a look.

Well, thank you very much.

**Comment by G356** [comment]
> It looks an issue of Xstream with JDK 11. Xstream is used for serializing and deserializing the model data as XML in Amateras Modeler. I don't know if we can fix the issue without breaking compatibility but will take a look.

The value of vm in the eclipse.ini file is changed to below jdk11 and it can be used normally.

**Comment by bailucool** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by davidbuenov** [comment]
> > It looks an issue of Xstream with JDK 11. Xstream is used for serializing and deserializing the model data as XML in Amateras Modeler. I don't know if we can fix the issue without breaking compatibility but will take a look.
> 
> The value of vm in the eclipse.ini file is changed to below jdk11 and it can be used normally.

I have tried with these parameters but it does not work. Can you put an example?
-vmargs
-Dosgi.requiredJavaVersion=9

**Comment by bailucool** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by stllh** [comment]
Even if 2020-12 and 2021-12 are incompatible, I want to use Amaterasu after 2021-12.
Is it difficult to choose between using Xstream or another method by setting options?
thanks.

**Comment by careycy** [comment]
> It looks an issue of Xstream with JDK 11. Xstream is used for serializing and deserializing the model data as XML in Amateras Modeler. I don't know if we can fix the issue without breaking compatibility but will take a look.

JDK 11 can be used, but you need to modify the JDK path used when eclipse starts. Eclipse uses its own JDK version by default. The minimum version used by the latest eclipse is JDK 17. Modify
/Applications/Eclipse.app/Contents/Eclipse/eclipse.ini

-vm
/Users/carey.z/.p2/pool/plugins/org.eclipse.justj.openjdk.hotspot.jre.full.macosx.x86_64_17.0.5.v20221102-0933/jre/lib/libjli.dylib
 
-vm
/Library/Java/JavaVirtualMachines/jdk-11.0.2.jdk/Contents/Home/bin/java

Changing to the local JDK 11 path can solve this problem

Eclipse IDE
Version: 2022-12 (4.26.0)
Build id: 20221201-1913
JDK version
java version "11.0.2" 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)

**Comment by careycy** [comment]
> > > It looks an issue of Xstream with JDK 11. Xstream is used for serializing and deserializing the model data as XML in Amateras Modeler. I don't know if we can fix the issue without breaking compatibility but will take a look.
> > 
> > 
> > The value of vm in the eclipse.ini file is changed to below jdk11 and it can be used normally.
> 
> I have tried with these parameters but it does not work. Can you put an example? -vmargs -Dosgi.requiredJavaVersion=9

https://github.com/takezoe/amateras-modeler/issues/22#issuecomment-1381467156

**Comment by careycy** [comment]
> Even if 2020-12 and 2021-12 are incompatible, I want to use Amaterasu after 2021-12. Is it difficult to choose between using Xstream or another method by setting options? thanks.

https://github.com/takezoe/amateras-modeler/issues/22#issuecomment-1381467156

**Comment by cypher256** [comment]
Cause:
```ini
converter           : com.thoughtworks.xstream.converters.reflection.SerializableConverter
message[1]          : 
Unable to make private void java.beans.PropertyChangeSupport.readObject(java.io.ObjectInputStream) 
throws java.lang.ClassNotFoundException,java.io.IOException accessible: 
module java.desktop does not "opens java.beans" to unnamed module 
```

You can work around this issue by adding the following to eclipse.ini.

``` ini
--add-opens=java.desktop/java.beans=ALL-UNNAMED
```

<br>

The module mechanism was introduced in Java 9 and later, and became strict and error in Java 16 and later, but specifying the library in --add-opens disables access restrictions.

I have published an Eclipse Distribution called Pleiades All in One, which includes my favorite Amateras Modeler, and have been experiencing this problem, which is why I came here. I will add this option to eclipse.ini in the next release of Pleiades All in One.

**Comment by davidbuenov** [comment]
Thank you Shinji, your contribution is very useful!!

**Comment by takezoe** [comment]
@cypher256 Thank you! For now, I will mention that option in README, but will look for a replacement of Xstream in long-term. Of course, backward-compatibility will be the biggest problem but I think the plugin can use the new solution for new files while using Xstream for reading old files.

**Comment by cypher256** [comment]
@takezoe 
Looking forward to the new solution!

**Comment by stllh** [comment]
Wonderful. Thank you very much.
I will do my best to support Amateras to be active again in the future eclipse.

**Comment by davidbuenov** [comment]
I have updated my video explaining how to use Amateras in Eclipse in Spanish. https://youtu.be/6ha62S8E_5I (in the comments)

**Comment by MASEOKJAE** [comment]
I'm currently experiencing the same issue... How did you resolve it? I tried changing the JDK to both 1.8 and 11... but it didn't work...

<img width="1134" alt="스크린샷 2024-03-20 오후 3 51 59" src="https://github.com/takezoe/amateras-modeler/assets/79703790/66957aaa-dd66-43e8-8693-d03d5d0daba2">
