### ISSUE TITLE
Not able to drag the clases into the box to create UML diagram

### ISSUE THREAD

**Issue by alopzop** [takezoe/amateras-modeler#28]
![Captura de pantalla 2023-11-30 233912](https://github.com/takezoe/amateras-modeler/assets/147827509/b8076bc6-d4b7-474a-8a34-b1aabe879a7d)
I am not able to drag the classes into the diagram box, do you know how to solve? it always open the classes.

Thanks

**Comment by fca758** [comment]
I have the same problem. Don´t know how to fix it.

**Comment by Marlrero** [comment]
I have the same problem.

**Comment by GivingupCoke** [comment]
I have the same problem.

**Comment by takezoe** [comment]
Released 2.2.0 with #27 and #30. Great thanks for @cypher256!!
