### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by want-to-ask** [takezoe/amateras-modeler#29]
I'm not able to install from URL https://takezoe.github.io/amateras-update-site/
What am I doing wrong?

After selecting the software packages to be installed I get the error message "Installing software has encountered a problem. An error occured while collecting items to be installed"

Error message in detail:
An error occurred while collecting items to be installed
session context was:(profile=XXX_eclipse_java-2022-09_eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.eclipse.jetty.webapp,10.0.15
No repository found containing: osgi.bundle,org.eclipse.jetty.xml,10.0.15
No repository found containing: osgi.bundle,org.eclipse.rap.tools.launch.rwt,3.25.0.20230413-1514

**Comment by takezoe** [comment]
Released 2.2.0 which supports the latest version of Eclipse. Could you try it?

Note that you still need to add `--add-opens=java.desktop/java.beans=ALL-UNNAMED` to eclipse.ini as mentioned in README.
