### ISSUE TITLE
cannot install from update-site

### ISSUE THREAD

**Issue by letitiaXu** [takezoe/amateras-modeler#5]
http://takezoe.github.io/amateras-update-site/

Unable to read repository at http://takezoe.github.io/amateras-update-site/content.jar.
Unable to read repository at http://takezoe.github.io/amateras-update-site/content.jar.
Connection reset

**Comment by alexanderlc** [comment]
https://takezoe.github.io/amateras-update-site/

**Comment by takezoe** [comment]
Updated README.md: 85fba98277cbc8704f46a80a7c3599919e5225bd
